### PR TITLE
Lc member list

### PR DESCRIPTION
**Pull request by brodul**
Can someone review my code? 
And give feedback about the directory structure of new files? 

I have written tests I hope there are not 'false positive', so that actually test my code.

### CODE REVIEW

**Comment by domenkozar** [comment]
- did you actually clickety-clickety test that template renders?
- no integration tests for template (do we want them)?

**Comment by brodul** [comment]
On 07/15/2012 11:04 AM, Domen Kožar wrote:

> - did you actually clickety-clickety test that template renders?
> - no integration tests for template (do we want them)?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/eestec/eestec.portal/pull/18#issuecomment-6990145

Yes,  clickety-clickety test works on that point. I had some problems
after I add the eestec addon. I can go to the correct URL without any
errors bit the list is not visible. So I will fix that.

If you can give me a hint on how to test if the view renders correctly,
I will write a test.

Tnx in advance

**Comment by domenkozar** [comment]
You have to use zope.testbrowser as shown here https://github.com/eestec/eestec.portal/blob/master/src/eestec/portal/tests/test_newsitem.py#L62

**Comment by zupo** [comment]
Yep, zope.testbrowser tests are good to have. Just keep in mind that these are functional tests, not unit tests. As in, don't test all possible edge-cases with testbrowser (use unit tests for that). Just walk through the "mainstream" scenario of how the view will be used.

**Comment by zupo** [comment]
About file structure. Since "member-list" will only be used on LCs, I would put them in content/lc.py. Do you have a strong opinion to do otherwise (browser/lc.py in your case)?

**Comment by brodul** [comment]
No, I don't mind.

What about the template?

**Comment by zupo** [comment]
Hmm, no idea, I haven't worked with Grok that much and I don't know where it searches for templates by default.

**Comment by brodul** [comment]
Clickety-clickety test passes. 

About the templates I put them in the /src/eestec/portal/browser/templates/listlcmembers.pt
The file name must match the view class name by default.

The only thing that is missing is the "browser test".

**Comment by zupo** [comment]
This one can be taken over by someone else willing to finish it. Should be very close.

**Pull request closed without merging**
