### PR TITLE
Issue 24

### PR DESCRIPTION
**Pull request by balkian**
This should fix issues #24 and #23 at last! :beers: 

@zupo or someone else, please check it in case I missed something...

### CODE REVIEW

**Comment by zupo** [comment]
1. Travis build timed out, I restarted it now.
2. Pull request seems legit, I wen't through the code and it looks exactly how I would want it to be.
3. There's one tiny nitpick: the "def event_published(context, event):" now contains two actions: published and cancelled. So let's rename the method name to "event_transitioned" and write in its docstring something like "in here we handle workflow transitions for Events, such as when event is published or when it is cancelled".

Good job!

**Comment by zupo** [comment]
Cool, so also Travis now agrees that this pull request can be merged, @balkian can you refactor the event_published method I mentioned above? I'll then merge this.

**Comment by balkian** [comment]
I would merge it myself, but I think it is a better practice that someone else does it.

Thanks :beer:

**Comment by zupo** [comment]
Yeah it's always better if someone else merges it, just so there's an extra pair of eyes going through changes.

**Comment by zupo** [comment]
Doing it right now.

**Comment by zupo** [comment]
Merged it manually, not sure why GitHub's UI doesn't pick it up?

**Pull request closed without merging**
